version: "3.3"
services:

    flask:
        build: .
        command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:passwd@postgres:5432/flask_db
        depends_on:
            - postgres

    postgres:
        image: postgres

        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=passwd
            - POSTGRES_DB=flask_db